services:
  migrations:
    build: .
    command: alembic upgrade head
    env_file: 
      - .env.dev
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4.3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  publisher:
    build: .
    volumes:
      - ./app:/app/app
    command: faststream run src.publisher:app --reload
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  consumer:
    build: .
    volumes:
      - ./app:/app/app
    command: faststream run src.consumer:app --reload
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
